name: daily-build-check

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  schedule:
    - cron: "0 3 * * *" # Daily at 3 AM

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]  # Add more Node.js versions as needed

    steps:
      - uses: actions/checkout@v4  # Checkout the code from the repo

      - name: Use Node.js ${{ matrix.node-version }}  # Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install frontend packages  # Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Install backend packages  # Install backend dependencies
        working-directory: ./backend
        run: npm install

      - name: Build application with docker
        working-directory: ./
        run: docker compose up -d --build

      - name: Wait for containers to be ready
        run: |
          sleep 30
          docker ps
      
      
