name: daily-build-check

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  schedule:
    - cron: "0 3 * * *" # Daily at 3 AM

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]  # Add more Node.js versions as needed

    steps:
      - uses: actions/checkout@v3  # Checkout the code from the repo

      - name: Use Node.js ${{ matrix.node-version }}  # Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"  # Cache npm dependencies

      - name: Install frontend packages  # Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build frontend  # Build the frontend application
        working-directory: ./frontend
        run: npm run build --if-present

      - name: Install backend packages  # Install backend dependencies
        working-directory: ./backend
        run: npm install

      - name: Run backend 
        working-directory: ./backend
        run: npm start &
        
      - name: Wait for backend to start  # Wait for the backend to initialize
        run: sleep 10

      - name: Run frontend tests & coverage 
        working-directory: ./frontend
        run: npm run coverage

      - name: Run backend tests & coverage
        working-directory: ./backend
        run: NODE_ENV=test nyc mocha --recursive --exit

      - name: Upload coverage to Codecov 
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
