name: CI

on:
  push:
    branches:
      - '**'  # Triggers on push to any branch
  pull_request:
    branches:
      - '**'  # Triggers on pull request to any branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'  # Use the latest LTS version of Node.js

    - name: Install dependencies
      run: npm ci  # Use npm ci for a clean install based on package-lock.json

    - name: Run tests
      run: npm test