# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install packages
        working-directory: ./frontend
        run: |
          npm i
      - name: Run build
        working-directory: ./frontend
        run: |
          npm run build --if-present

      # - name: Run tests
      #   working-directory: ./frontend
      #   run: |
      #     npm run test
      - name: Run tests & coverage
        working-directory: ./frontend
        run: |
          npm run coverage
      - name: Upload coverage to Codecov
        # working-directory: ./frontend
        uses: codecov/codecov-action@v1
        with:
          path: /frontend/coverage
          token: ${{ secrets.CODECOV_TOKEN }}
      # - run: ls -al
      # - run: cd frontend
      # - run: ls -al
      # - run: cd frontend
      # - run: npm ci
      # - run: npm run build --if-present
      # - run: npm test
