name: prettier-check

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          
          # Prettier check on frontend, fixes if failure
          # Will be red fail if errors
      - name: Run Prettier check in frontend folder
        run: npx prettier --check frontend/**
      - name: Auto-fix Prettier issues in frontend folder
        if: failure()
        run: npx prettier --write frontend/**

          # Prettier check on frontend, fixes if failure
          # Will be red fail if errors
      - name: Run Prettier check in backend folder
        run: npx prettier --check backend/**
      - name: Auto-fix Prettier issues in backend folder
        if: failure()
        run: npx prettier --write backend/**

